name: Dev

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - 'develop'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.0

      - name: Setup Android SDK
        run: sdkmanager platform-tools

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_apikey=${{ secrets.BINTRAY_KEY }}

      - name: Assemble libraries
        run: ./gradlew assembleRelease -Pbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_apikey=${{ secrets.BINTRAY_KEY }}
